### ISSUE TITLE
Discussion about size

### ISSUE THREAD

**Issue by John1231983** [CASIA-IVA-Lab/TDKD#2]
In your code, you have
```
		print("pos.shape=", pos.shape)

		pos_part1 = pos[:, 0:12800]
		pos_part2 = pos[:, 12800:16000]
		pos_part3 = pos[:, 16000:]

		cls_part1 = (neg[:, 0:12800] + pos_part1) > 0
		cls_part2 = (neg[:, 12800:16000] + pos_part2) > 0
		cls_part3 = (neg[:, 16000:] + pos_part3) > 0
```
Could you explain why you choose ` 0:12800`, `12800:16000` and `16000:`? If I change the width of teacher from 3 to 5, does these above number still same?

**Comment by icekrn** [comment]
Since RetinaFace has three prediction branches, and the resolution of each image during training is `640*640`. The first prediction branch starts from `stride=8`, so the feature map size is `80*80=6400`. At the same time, each pixel on the feature map corresponds to two anchors of different sizes(16 and 32), so there are a total of `6400*2=12800` anchors. The latter two branches are the same. The number of channels is not involved here, if you want to change the width of the teacher, you can see `models/distill_loss.py` for details.
